# Brewfile for my personal computer
# here is a change to my brewfile
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "thoughtbot/formulae"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "git"
brew "hub"
brew "libksba"
brew "libtool"
brew "libyaml"
brew "openssl"
brew "readline"
brew "python"
brew "macvim"
brew "mas"
brew "openssl@1.1"
brew "pkg-config"
brew "vim"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "atom"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "slack"
cask "spotify"
mas "Alfred", id: 405843582
mas "GIPHY CAPTURE", id: 668208984
mas "iA Writer", id: 775737590
mas "Twitter", id: 409789998
